#Change the name to match your course name

#Example name: Deploy HTML Files to AppService - COURSENAME

name: Deploy HTML Files to AppService - CMST385

on:

  push:

    branches:

      - main

jobs:

  build-and-deploy:

    runs-on: windows-latest

     steps:

    - uses: actions/checkout@main

    - name: Deploy to Azure Web App

      uses: azure/webapps-deploy@v1

      with:

      #Change the app-name to match what was provided to you in the publish settings file, this is in a naming convention of 'COURSENAME-STUDENTUID'

        app-name: 'CMST385-kjezwinski'

        slot-name: 'production'

      #Change the publish profile to match what you named your secret setup in GitHub, Example shown below

        publish-profile: ${{ secrets.AppServiceCMST385 }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
